/**
* @param appid Indicates the appID provided from telebirr
* @param appkey Indicates the appKey provided by telebirr platform
* @param baseUrl Indicates the base url of the telebirr platform
* @param publicKey Indicates the publicKey provided from telebirr
**/
export interface Iclient {
    appid: string;
    appkey: string;
    publicKey: string;
    baseUrl: string;
}


/**
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 */
export interface IRequestReq {
    notifyUrl: string;
    timeoutExpress: string;
}

/**
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
**/
export interface IReceiver {
    receiveName: string;
    shortCode: string;
}


/**
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param nonce Indicates a unique random string generated by third party system
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
**/
export interface ITransaction {
    outTradeNo: string;
    nonce: string;
    subject: string;
    totalAmount: string;
}


/**
 * @param appid Indicates the appID provided from telebirr
 * @param ussid Encryption service parameters string
 * @param sign  Sign 
**/
export interface IRequestBody {
    appid: string;
    ussid: string;
    sign: string;
}

/**
 * @param appid Indicates the appID provided from telebirr
 * @param ussid Encryption service parameters string
 * @param sign  Sign 
**/
export interface IRequestBodyPre {
    appid: string;
    ussid: IUssid;
    sign: IStringA;
}

/**
 * @param appid Indicates the appID provided from telebirr 
 * @param nonce Indicates a unique random string generated by third party system
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 * @param timestamp Indicates the time stamp on the request message. The timestamp should be in milliseconds
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
 */
export interface IUssid extends IRequestReq, IReceiver, ITransaction {
    appid: string;
    timestamp: string;
}

/**
 * @param appid Indicates the appID provided from telebirr 
 * @param nonce Indicates a unique random string generated by third party system
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 * @param timestamp Indicates the time stamp on the request message. The timestamp should be in milliseconds
 * @param returnUrl Indicates third party redirect page URL after the payment completed
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
 */
export interface IH5Ussid extends IUssid {
    returnUrl: string
}

/**
 * @param appid Indicates the appID provided from telebirr 
 * @param nonce Indicates a unique random string generated by third party system
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 * @param timestamp Indicates the time stamp on the request message. The timestamp should be in milliseconds
 * @param returnApp Indicates third party redirect app URL after the payment completed
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
 */
export interface InAppUssid extends IUssid {
    returnApp: string
}

/**
 * @param appid Indicates the appID provided from telebirr 
 * @param appkey Indicates the appKey provided by telebirr platform
 * @param nonce Indicates a unique random string generated by third party system
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 * @param timestamp Indicates the time stamp on the request message. The timestamp should be in milliseconds
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
 */
export interface IStringA extends IRequestReq, IReceiver, ITransaction {
    appid: string;
    appkey: string;
    timestamp: string;
}

/**
 * @param appid Indicates the appID provided from telebirr 
 * @param appkey Indicates the appKey provided by telebirr platform
 * @param nonce Indicates a unique random string generated by third party system
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 * @param timestamp Indicates the time stamp on the request message. The timestamp should be in milliseconds
 * @param returnUrl Indicates third party redirect page URL after the payment completed
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
 */
export interface IH5StringA extends IStringA {
    returnUrl: string
}

/**
 * @param appid Indicates the appID provided from telebirr 
 * @param appkey Indicates the appKey provided by telebirr platform
 * @param nonce Indicates a unique random string generated by third party system
 * @param notifyUrl Indicates the end point URL from third party which will be used by telebirr platform to respond the Payment result
 * @param outTradeNo Indicates the third party payment transaction order number that will be generated by third party system and it shall be unique
 * @param receiveName Indicates the name of the person/organization who will receive the payment
 * @param shortCode Indicates third party  Short Code provided from telebirr
 * @param subject Indicates the item or any other name for the payment that is being issued by the customer
 * @param timeoutExpress Indicates the payment Order request timeout from third party which indicates the time for payment process to be ended. After this time the payment will not be processed and third party system can reinitiate again,the parameter value unit is Minutes
 * @param timestamp Indicates the time stamp on the request message. The timestamp should be in milliseconds
 * @param returnApp Indicates third party redirect returnApp URL after the payment completed
 * @param totalAmount Indicates the order amount in ETB. The value ranges from 0.01 to 100000000.00 and is accurate to two decimal places, The value will be authenticated by telebirr platform depending on the limit rule assigned to the customer
 */
export interface IInAppStringA extends IStringA {
    returnApp: string
}

export type Treturn = { returnApp?: string; returnUrl?: string };
/**
 *  @param code Indicates the response code from telebirr platform
 *  @param msg Indicates the response message from telebirr platform
**/

export interface IResponse {
    code: string;
    message: string;
}

/**
 *  @param code Indicates the response code from telebirr platform
 *  @param msg Indicates the response message from telebirr platform
 *  @param outTradeNo Indicates the third party payment request order number stated on the payment request. 
 *  @param tradeNo Indicates the transaction  number in telebirr payment system
**/
export interface INotificationIRespons extends IResponse {
    data: {
        outTradeNo: string;
        tradeNo: string;
    }
}

/**
 *  @param code Indicates the response code from telebirr platform
 *  @param msg Indicates the response message from telebirr platform
 *  @param data Indicates the response data from telebirr platform
 *  @param toPayUrl Indicates the payment URL from telebirr platform
 */
export interface IH5webResponse extends IResponse {
    data: {
        toPayUrl: string
    }
}

/**
*  @param code Indicates the response code from telebirr platform
 *  @param msg Indicates the response message from telebirr platform
 *  @param data Indicates the response data from telebirr platform
 *  @param toPayMsg Msg for redirecting to  telebirr App Payment for android use IAndroidAppResponse for ios its just a string url
 */
export interface IInAppResponse extends IResponse {
    data: {
        toPayMsg: string
    }
}

/**
 *  @param PackageName cn.tydic.ethiopay
 *  @param Activity cn.tydic.ethiopay.PayForOtherAppActivity
**/
export interface IMobileApppResponse {
    PackageName: string;
    Activity: string;
}